### ISSUE TITLE
[RaedZorkot] sample kivy GUI app for wrapping interaction with IB TWS API

### ISSUE THREAD

**Issue by shadiakiki1986** [teamshadi/ssoc18#14]
Hi @RaedZorkot

While we wait for the IB credentials for a paper trading account, let's start with build a Graphical User Interface that will wrap the code that will fetch prices from IB TWS.

We will use [kivy](https://kivy.org/) as it's cross-platform, based on python, and well-maintained.

Steps
- [ ] build the hello world application documented on kivy's home page (~1h)
- [ ] start a new kivy application that will have (~5h)
  - main menu will be just 3 buttons: prices, portfolio, trades
  - when `prices` is clicked, it should display a [pandas](http://pandas.pydata.org/) dataframe
    - let's use `import pandas as pd; df = pd.DataFrame({'symbol': ['a','b','c'], 'close': [100, 120, 90]})` for now
  - when `portfolio` is clicked, it should show another pandas dataframe
    - let's use `import pandas as pd; df = pd.DataFrame({'symbol': ['a','b','c'], 'position': [1,2,3]})` for now
  - when `trades` is clicked, it should show another pandas dataframe
    - let's use `import pandas as pd; df = pd.DataFrame({'symbol': ['a','b','c'], 'qty': [1, -1, 0]})` for now

**Comment by RaedZorkot** [comment]
<img width="828" alt="screen shot 2018-07-19 at 5 38 51 pm" src="https://user-images.githubusercontent.com/24481362/42949652-eb61e2f8-8b7a-11e8-84b8-1197b3f12b55.png">
<img width="816" alt="screen shot 2018-07-19 at 5 38 41 pm" src="https://user-images.githubusercontent.com/24481362/42949654-eb916a3c-8b7a-11e8-9ef6-264af3c33f81.png">
<img width="862" alt="screen shot 2018-07-19 at 5 38 32 pm" src="https://user-images.githubusercontent.com/24481362/42949655-ebbb462c-8b7a-11e8-9f42-a1f20676dff5.png">
These 3 pictures show the menu bar with the 3 different pages ( Trades, Portfolio, Prices)
<img width="818" alt="screen shot 2018-07-19 at 5 42 27 pm" src="https://user-images.githubusercontent.com/24481362/42949754-214408ce-8b7b-11e8-9fe8-61d17f37f54f.png">
And this picture shows the pandas dataframe as a list, the problem is the overlapping with the menu bar

**Comment by shadiakiki1986** [comment]
migrated to https://github.com/SSOC18/ib-kivy/issues/2
